FROM golang:1.13-alpine

ARG CADDY_VERSION

# install git
RUN apk add --no-cache git

# clone caddy
RUN git clone --branch  ${CADDY_VERSION} https://github.com/mholt/caddy mholt/caddy 

# clone builder
RUN git clone https://github.com/caddyserver/caddy  caddyserver/caddy

RUN mkdir -p /var/www/html
COPY index.html /var/www/html/index.html

#Disable Caddy Telemetry
RUN sed -i 's/var EnableTelemetry = true/var EnableTelemetry = false/' /root/mholt/caddy/caddy/caddymain/run.go

# build caddy
WORKDIR /root/mholt/caddy/caddy
RUN go install

RUN cp $GOPATH/bin/caddy /usr/local/bin/

WORKDIR /var/www/html
